services:
  db:
    image: postgres:15
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "8202:5432"

  backend:
    build: ./server
    container_name: todo-backend
    ports:
      - "8201:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: todo_db

  frontend:
    build: ./angular
    container_name: todo-frontend
    ports:
      - "8200:4200"
    depends_on:
      - backend
