name: Deploy Docker App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-app:latest .

      - name: Push da imagem Docker
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todo-app:latest

      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Copiar código e docker-compose para servidor remoto
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "~/app"

      - name: Executar análise SonarQube no servidor remoto
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker run -d --name sonarqube -p 8905:9000 sonarqube
            sleep 60  # espera o Sonar subir
            cd ~/app
            sonar-scanner \
              -Dsonar.projectKey=meu-projeto \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://localhost:8905 \
              -Dsonar.login=admin \
              -Dsonar.password=admin
            docker stop sonarqube && docker rm sonarqube

      - name: Deploy da aplicação no servidor
        run: |
          ssh -o StrictHostKeyChecking=no aluno@201.23.3.86 << 'EOF'
            docker stop todo-app || true
            docker rm todo-app || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/todo-app:latest
            docker run -d --name todo-app -p 8204:3000 -p 8205:4200 -p 8202:5432 ${{ secrets.DOCKER_USERNAME }}/todo-app:latest
          EOF
