name: Deploy Docker App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-app:latest .

      - name: Push da imagem Docker
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todo-app:latest

      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Copiar arquivos para o servidor
        run: |
          ssh -o StrictHostKeyChecking=no aluno@201.23.3.86 "mkdir -p ~/todo-deploy"
          scp -r . aluno@201.23.3.86:~/todo-deploy

      - name: Rodar análise SonarQube no servidor
        run: |
          ssh -o StrictHostKeyChecking=no aluno@201.23.3.86 << 'EOF'
            cd ~/todo-deploy
            docker rm -f sonar || true
            docker run -d --name sonar -p 8203:9000 sonarqube:latest
            echo "Esperando o SonarQube iniciar..."
            sleep 60
            sonar-scanner \
              -Dsonar.projectKey=todo-app \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://localhost:8203 \
              -Dsonar.login=admin \
              -Dsonar.password=admin || { echo "Análise SonarQube falhou"; exit 1; }
            docker stop sonar
            docker rm sonar
          EOF

      - name: Deploy da aplicação no servidor
        run: |
          ssh -o StrictHostKeyChecking=no aluno@201.23.3.86 << 'EOF'
            docker stop todo-app || true
            docker rm todo-app || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/todo-app:latest
            docker run -d --name todo-app -p 8204:3000 -p 8205:4200 -p 8202:5432 ${{ secrets.DOCKER_USERNAME }}/todo-app:latest
          EOF
